"""
generate_seed.py
Generates supabase/seed.sql from recipe_data.py.
Re-run whenever recipes are added or changed.
Usage: python3 supabase/generate_seed.py
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from recipe_data import RECIPES

def s(val):
    if val is None:
        return 'NULL'
    return "'" + str(val).replace("'", "''") + "'"

def j(obj):
    return s(json.dumps(obj, ensure_ascii=False))

rows = []
for r in RECIPES:
    rows.append(
        f"  ({s(r['id'])}, NULL, {s(r['name'])}, {s(r['tier'])}, {s(r['tier_label'])},\n"
        f"   {s(r['chef'])}, {s(r['description'])},\n"
        f"   {s(r['time'])}, {s(r['servings'])},\n"
        f"   {j(r['ingredients'])},\n"
        f"   {j(r['steps'])},\n"
        f"   {j(r['macros'])},\n"
        f"   {s(r['perf_tip'])})"
    )

out = os.path.join(os.path.dirname(__file__), "seed.sql")
with open(out, "w", encoding="utf-8") as f:
    f.write("-- Auto-generated by supabase/generate_seed.py — do not edit manually.\n\n")
    f.write("insert into public.recipes\n")
    f.write("  (id, user_id, name, tier, tier_label, chef, description,\n")
    f.write("   time_label, servings, ingredients, steps, macros, perf_tip)\n")
    f.write("values\n")
    f.write(",\n".join(rows))
    f.write("\non conflict (id) do nothing;\n")

print(f"✅  Generated: {out}  ({len(RECIPES)} recipes)")
