"""
Grocery & pantry data for Vidya's Vegetarian Performance Cookbook.
Each ingredient maps to a list of recipe IDs that use it.
GENERAL_PANTRY items are standalone (not tied to a specific recipe).
"""

# Recipe short-name lookup (id -> display name)
RECIPE_NAMES = {
  "berry-chia-pudding":   "Chia Pudding",
  "yogurt-parfait":       "Yogurt Parfait",
  "avocado-egg-toast":    "Avocado Toast",
  "date-energy-bites":    "Energy Bites",
  "chickpea-wrap":        "Chickpea Wrap",
  "tofu-scramble":        "Tofu Scramble",
  "shakshuka":            "Shakshuka",
  "quinoa-bowl":          "Quinoa Bowl",
  "bean-tacos":           "Bean Tacos",
  "fried-rice":           "Fried Rice",
  "miso-noodles":         "Miso Noodles",
  "chickpea-salad":       "Chickpea Salad",
  "lentil-soup":          "Lentil Soup",
  "caprese-toast":        "Caprese Toast",
  "enchiladas":           "Enchiladas",
  "mushroom-risotto":     "Mushroom Risotto",
  "tikka-masala":         "Tikka Masala",
  "thai-curry":           "Thai Curry",
  "zucchini-fritters":    "Zucchini Fritters",
  "stuffed-peppers":      "Stuffed Peppers",
  "buddha-bowl":          "Buddha Bowl",
  "stuffed-shells":       "Stuffed Shells",
  "saag-paneer":          "Saag Paneer",
  "red-lentil-dal":       "Red Lentil Dal",
  "moroccan-stew":        "Moroccan Stew",
  "veg-chili":            "Veg Chili",
  "minestrone":           "Minestrone",
  "tomato-bean-soup":     "Tomato Bean Soup",
  "veg-biryani":          "Veg Biryani",
  "kale-salad":           "Kale Salad",
  "roasted-chickpeas":    "Roasted Chickpeas",
  "rice-cakes-hummus":    "Rice Cakes",
  "trail-mix":            "Trail Mix",
  "apple-almond-butter":  "Apple & Almond Butter",
  "hard-boiled-eggs":     "Boiled Eggs",
  "edamame-salt":         "Edamame",
  "cheese-crackers":      "Cheese & Crackers",
  "banana-pb":            "Banana & PB",
}

# ── INGREDIENT CATEGORIES ──────────────────────────────────────────────────
# Each entry: { "name": str, "recipes": [recipe_id, ...] }
# "recipes": [] means general pantry / not recipe-specific

GROCERY_CATEGORIES = [
  {
    "id": "produce",
    "label": "🥬 Fresh Produce",
    "items": [
      {"name": "Apple",                "recipes": ["apple-almond-butter"]},
      {"name": "Avocado",              "recipes": ["avocado-egg-toast", "bean-tacos", "buddha-bowl"]},
      {"name": "Baby spinach",         "recipes": ["chickpea-wrap", "tofu-scramble", "mushroom-risotto"]},
      {"name": "Banana",               "recipes": ["banana-pb"]},
      {"name": "Basil, fresh",         "recipes": ["caprese-toast", "minestrone", "tomato-bean-soup"]},
      {"name": "Bell peppers, red",    "recipes": ["shakshuka", "thai-curry", "veg-chili", "stuffed-peppers"]},
      {"name": "Bell peppers (large, for stuffing)", "recipes": ["stuffed-peppers"]},
      {"name": "Broccoli florets",     "recipes": ["buddha-bowl"]},
      {"name": "Carrots",              "recipes": ["lentil-soup", "moroccan-stew", "minestrone", "veg-biryani"]},
      {"name": "Cauliflower",          "recipes": ["veg-biryani"]},
      {"name": "Celery",               "recipes": ["minestrone"]},
      {"name": "Cherry tomatoes",      "recipes": ["quinoa-bowl", "chickpea-salad", "caprese-toast", "stuffed-peppers", "tofu-scramble"]},
      {"name": "Coriander / cilantro, fresh", "recipes": ["bean-tacos", "tikka-masala", "red-lentil-dal", "moroccan-stew", "veg-biryani", "veg-chili"]},
      {"name": "Cucumber",             "recipes": ["quinoa-bowl", "chickpea-salad", "chickpea-wrap", "zucchini-fritters", "rice-cakes-hummus"]},
      {"name": "Dill, fresh",          "recipes": ["zucchini-fritters"]},
      {"name": "Edamame, frozen",      "recipes": ["miso-noodles", "edamame-salt"]},
      {"name": "Garlic",               "recipes": ["shakshuka", "quinoa-bowl", "bean-tacos", "fried-rice", "miso-noodles", "chickpea-salad", "lentil-soup", "caprese-toast", "enchiladas", "mushroom-risotto", "tikka-masala", "thai-curry", "zucchini-fritters", "stuffed-peppers", "buddha-bowl", "stuffed-shells", "saag-paneer", "red-lentil-dal", "moroccan-stew", "veg-chili", "minestrone", "tomato-bean-soup", "veg-biryani", "kale-salad"]},
      {"name": "Ginger, fresh",        "recipes": ["fried-rice", "miso-noodles", "tikka-masala", "saag-paneer", "red-lentil-dal", "veg-biryani", "tofu-scramble"]},
      {"name": "Green beans",          "recipes": ["minestrone"]},
      {"name": "Green chilli",         "recipes": ["saag-paneer", "red-lentil-dal"]},
      {"name": "Jalapeño",             "recipes": ["bean-tacos"]},
      {"name": "Kaffir lime leaves",   "recipes": ["thai-curry"]},
      {"name": "Kale",                 "recipes": ["buddha-bowl", "kale-salad"]},
      {"name": "Lemon",                "recipes": ["quinoa-bowl", "chickpea-wrap", "lentil-soup", "caprese-toast", "zucchini-fritters", "stuffed-peppers", "buddha-bowl", "red-lentil-dal", "kale-salad"]},
      {"name": "Lime",                 "recipes": ["bean-tacos", "thai-curry"]},
      {"name": "Mango",                "recipes": ["bean-tacos"]},
      {"name": "Mint, fresh",          "recipes": ["quinoa-bowl", "zucchini-fritters", "veg-biryani"]},
      {"name": "Mixed berries",        "recipes": ["berry-chia-pudding", "yogurt-parfait"]},
      {"name": "Mixed mushrooms",      "recipes": ["mushroom-risotto"]},
      {"name": "Onion (white / yellow)", "recipes": ["shakshuka", "lentil-soup", "enchiladas", "mushroom-risotto", "tikka-masala", "saag-paneer", "red-lentil-dal", "moroccan-stew", "veg-chili", "minestrone", "tomato-bean-soup", "veg-biryani"]},
      {"name": "Onion, red",           "recipes": ["quinoa-bowl", "bean-tacos", "chickpea-wrap", "chickpea-salad", "buddha-bowl", "kale-salad"]},
      {"name": "Parsley, fresh",       "recipes": ["shakshuka", "quinoa-bowl", "stuffed-peppers"]},
      {"name": "Peas, frozen",         "recipes": ["fried-rice", "veg-biryani"]},
      {"name": "Potato",               "recipes": ["veg-biryani"]},
      {"name": "Red cabbage",          "recipes": ["kale-salad"]},
      {"name": "Rocket / arugula",     "recipes": ["avocado-egg-toast"]},
      {"name": "Spring onions",        "recipes": ["fried-rice", "miso-noodles", "tofu-scramble", "zucchini-fritters"]},
      {"name": "Sugar snap peas",      "recipes": ["thai-curry"]},
      {"name": "Sweet potato",         "recipes": ["enchiladas", "moroccan-stew", "buddha-bowl"]},
      {"name": "Thai basil, fresh",    "recipes": ["thai-curry"]},
      {"name": "Thyme, fresh",         "recipes": ["mushroom-risotto"]},
      {"name": "Tomatoes, vine",       "recipes": ["tomato-bean-soup"]},
      {"name": "Tomatoes, fresh (ripe)", "recipes": ["caprese-toast"]},
      {"name": "Zucchini",             "recipes": ["thai-curry", "zucchini-fritters", "stuffed-peppers", "buddha-bowl", "minestrone"]},
      {"name": "Corn kernels (fresh or frozen)", "recipes": ["zucchini-fritters", "veg-chili"]},
    ]
  },

  {
    "id": "dairy",
    "label": "🥚 Dairy & Eggs",
    "items": [
      {"name": "Butter (cold)",        "recipes": ["mushroom-risotto"]},
      {"name": "Cheddar, grated",      "recipes": ["enchiladas", "cheese-crackers"]},
      {"name": "Eggs",                 "recipes": ["avocado-egg-toast", "shakshuka", "fried-rice", "zucchini-fritters", "stuffed-shells", "hard-boiled-eggs"]},
      {"name": "Feta cheese",          "recipes": ["chickpea-wrap", "quinoa-bowl", "chickpea-salad", "zucchini-fritters", "stuffed-peppers", "kale-salad"]},
      {"name": "Fresh mozzarella",     "recipes": ["caprese-toast"]},
      {"name": "Ghee",                 "recipes": ["saag-paneer", "red-lentil-dal", "veg-biryani"]},
      {"name": "Greek yogurt",         "recipes": ["yogurt-parfait", "bean-tacos", "enchiladas", "tikka-masala", "zucchini-fritters", "saag-paneer", "veg-biryani"]},
      {"name": "Heavy cream",          "recipes": ["tikka-masala"]},
      {"name": "Milk (dairy or oat)",  "recipes": ["berry-chia-pudding"]},
      {"name": "Paneer",               "recipes": ["saag-paneer"]},
      {"name": "Parmesan",             "recipes": ["mushroom-risotto", "stuffed-shells", "minestrone"]},
      {"name": "Ricotta",              "recipes": ["stuffed-shells"]},
    ]
  },

  {
    "id": "pantry",
    "label": "🫘 Grains, Legumes & Canned",
    "items": [
      {"name": "Arborio rice",         "recipes": ["mushroom-risotto"]},
      {"name": "Basmati rice",         "recipes": ["veg-biryani", "tikka-masala", "red-lentil-dal"]},
      {"name": "Black beans, canned",  "recipes": ["bean-tacos", "enchiladas", "veg-chili"]},
      {"name": "Brown rice",           "recipes": ["fried-rice", "buddha-bowl"]},
      {"name": "Cannellini beans, canned", "recipes": ["caprese-toast", "minestrone", "tomato-bean-soup"]},
      {"name": "Chickpeas, canned",    "recipes": ["chickpea-wrap", "chickpea-salad", "stuffed-peppers", "buddha-bowl", "moroccan-stew", "kale-salad", "roasted-chickpeas"]},
      {"name": "Coconut milk, canned", "recipes": ["berry-chia-pudding", "thai-curry", "red-lentil-dal"]},
      {"name": "Corn tortillas",       "recipes": ["bean-tacos", "enchiladas"]},
      {"name": "Crushed tomatoes, canned", "recipes": ["shakshuka", "tikka-masala", "red-lentil-dal", "moroccan-stew", "veg-chili", "minestrone"]},
      {"name": "Enchilada sauce, jarred", "recipes": ["enchiladas"]},
      {"name": "Jasmine rice",         "recipes": ["thai-curry"]},
      {"name": "Kidney beans, canned", "recipes": ["veg-chili"]},
      {"name": "Large pasta shells (conchiglioni)", "recipes": ["stuffed-shells"]},
      {"name": "Lentils, red (dry)",   "recipes": ["lentil-soup", "red-lentil-dal"]},
      {"name": "Marinara / passata",   "recipes": ["stuffed-shells"]},
      {"name": "Nori sheets",          "recipes": ["miso-noodles"]},
      {"name": "Pinto beans, canned",  "recipes": ["veg-chili"]},
      {"name": "Quinoa",               "recipes": ["quinoa-bowl", "stuffed-peppers", "kale-salad"]},
      {"name": "Small pasta (ditalini / elbow)", "recipes": ["minestrone"]},
      {"name": "Soba noodles",         "recipes": ["miso-noodles"]},
      {"name": "Sourdough bread",      "recipes": ["avocado-egg-toast", "caprese-toast", "tomato-bean-soup"]},
      {"name": "Vegetable stock",      "recipes": ["quinoa-bowl", "miso-noodles", "lentil-soup", "mushroom-risotto", "red-lentil-dal", "moroccan-stew", "veg-chili", "minestrone", "tomato-bean-soup", "veg-biryani"]},
      {"name": "Whole-wheat tortillas","recipes": ["chickpea-wrap"]},
      {"name": "Whole-grain rice cakes", "recipes": ["rice-cakes-hummus"]},
      {"name": "Whole-grain seed crackers", "recipes": ["cheese-crackers"]},
    ]
  },

  {
    "id": "nuts",
    "label": "🥜 Nuts, Seeds & Dried Fruit",
    "items": [
      {"name": "Almond butter",        "recipes": ["berry-chia-pudding", "date-energy-bites", "apple-almond-butter"]},
      {"name": "Almonds, raw",         "recipes": ["yogurt-parfait", "date-energy-bites", "moroccan-stew", "trail-mix"]},
      {"name": "Chia seeds",           "recipes": ["berry-chia-pudding"]},
      {"name": "Coconut flakes",       "recipes": ["date-energy-bites"]},
      {"name": "Dark chocolate chips (70%+)", "recipes": ["date-energy-bites", "trail-mix"]},
      {"name": "Dates, medjool",       "recipes": ["date-energy-bites"]},
      {"name": "Dried apricots",       "recipes": ["moroccan-stew", "trail-mix"]},
      {"name": "Dried cranberries",    "recipes": ["kale-salad", "trail-mix"]},
      {"name": "Honey",                "recipes": ["yogurt-parfait", "bean-tacos", "buddha-bowl", "kale-salad", "apple-almond-butter", "banana-pb"]},
      {"name": "Kalamata olives",      "recipes": ["chickpea-salad"]},
      {"name": "Maple syrup",          "recipes": ["berry-chia-pudding", "kale-salad"]},
      {"name": "Peanut butter",        "recipes": ["banana-pb"]},
      {"name": "Pepitas / pumpkin seeds", "recipes": ["yogurt-parfait", "kale-salad", "trail-mix"]},
      {"name": "Puffed amaranth / puffed rice", "recipes": ["yogurt-parfait"]},
      {"name": "Sesame seeds",         "recipes": ["miso-noodles", "fried-rice"]},
      {"name": "Sunflower seeds",      "recipes": ["yogurt-parfait"]},
      {"name": "Tahini",               "recipes": ["buddha-bowl", "kale-salad"]},
      {"name": "Walnuts",              "recipes": ["berry-chia-pudding", "trail-mix"]},
    ]
  },

  {
    "id": "condiments",
    "label": "🫙 Oils, Sauces & Condiments",
    "items": [
      {"name": "Balsamic glaze",       "recipes": ["chickpea-wrap", "caprese-toast"]},
      {"name": "Brown sugar",          "recipes": ["thai-curry", "veg-chili"]},
      {"name": "Cocoa powder",         "recipes": ["veg-chili"]},
      {"name": "Coconut oil",          "recipes": ["red-lentil-dal"]},
      {"name": "Dry white wine",       "recipes": ["mushroom-risotto"]},
      {"name": "Green curry paste",    "recipes": ["thai-curry"]},
      {"name": "Harissa paste",        "recipes": ["moroccan-stew"]},
      {"name": "Hummus",               "recipes": ["chickpea-wrap", "rice-cakes-hummus"]},
      {"name": "Miso paste, white",    "recipes": ["miso-noodles"]},
      {"name": "Neutral cooking oil",  "recipes": ["fried-rice", "miso-noodles", "tikka-masala", "thai-curry", "saag-paneer", "veg-biryani"]},
      {"name": "Olive oil, extra virgin", "recipes": ["avocado-egg-toast", "shakshuka", "quinoa-bowl", "chickpea-wrap", "chickpea-salad", "lentil-soup", "caprese-toast", "enchiladas", "mushroom-risotto", "stuffed-peppers", "buddha-bowl", "minestrone", "tomato-bean-soup", "roasted-chickpeas", "rice-cakes-hummus", "apple-almond-butter", "hard-boiled-eggs"]},
      {"name": "Red wine vinegar",     "recipes": ["chickpea-salad"]},
      {"name": "Sesame oil",           "recipes": ["fried-rice", "miso-noodles"]},
      {"name": "Soy sauce / tamari",   "recipes": ["fried-rice", "miso-noodles", "thai-curry", "tofu-scramble"]},
      {"name": "Vanilla extract",      "recipes": ["berry-chia-pudding", "yogurt-parfait", "date-energy-bites"]},
      {"name": "Wholegrain mustard / mango chutney", "recipes": ["cheese-crackers"]},
    ]
  },

  {
    "id": "spices",
    "label": "🌶 Spices & Dried Herbs",
    "items": [
      {"name": "Bay leaves",           "recipes": ["veg-biryani"]},
      {"name": "Biryani masala",       "recipes": ["veg-biryani"]},
      {"name": "Cardamom pods, whole", "recipes": ["veg-biryani"]},
      {"name": "Chilli flakes",        "recipes": ["avocado-egg-toast", "shakshuka", "lentil-soup", "red-lentil-dal", "tomato-bean-soup"]},
      {"name": "Chilli powder",        "recipes": ["enchiladas", "veg-chili"]},
      {"name": "Cinnamon, ground",     "recipes": ["moroccan-stew"]},
      {"name": "Cinnamon stick",       "recipes": ["veg-biryani"]},
      {"name": "Cloves, whole",        "recipes": ["veg-biryani"]},
      {"name": "Coriander, ground",    "recipes": ["tikka-masala", "red-lentil-dal"]},
      {"name": "Cumin, ground",        "recipes": ["shakshuka", "bean-tacos", "lentil-soup", "enchiladas", "tikka-masala", "stuffed-peppers", "buddha-bowl", "red-lentil-dal", "moroccan-stew", "veg-chili", "tofu-scramble", "roasted-chickpeas"]},
      {"name": "Cumin seeds",          "recipes": ["saag-paneer", "red-lentil-dal", "veg-biryani"]},
      {"name": "Dried oregano",        "recipes": ["chickpea-salad", "veg-chili", "minestrone"]},
      {"name": "Dried rosemary",       "recipes": ["minestrone"]},
      {"name": "Dried thyme",          "recipes": ["minestrone", "tomato-bean-soup"]},
      {"name": "Everything bagel seasoning", "recipes": ["avocado-egg-toast", "hard-boiled-eggs"]},
      {"name": "Garam masala",         "recipes": ["tikka-masala", "saag-paneer", "red-lentil-dal"]},
      {"name": "Nutmeg",               "recipes": ["stuffed-shells"]},
      {"name": "Ras el hanout",        "recipes": ["moroccan-stew"]},
      {"name": "Saffron",              "recipes": ["veg-biryani"]},
      {"name": "Smoked paprika",       "recipes": ["shakshuka", "bean-tacos", "enchiladas", "buddha-bowl", "veg-chili", "tofu-scramble", "roasted-chickpeas", "rice-cakes-hummus", "hard-boiled-eggs"]},
      {"name": "Sumac",                "recipes": ["chickpea-wrap"]},
      {"name": "Turmeric",             "recipes": ["lentil-soup", "tikka-masala", "saag-paneer", "red-lentil-dal", "tofu-scramble"]},
      {"name": "White pepper",         "recipes": ["fried-rice"]},
      {"name": "Za'atar",              "recipes": ["hard-boiled-eggs"]},
    ]
  },

  {
    "id": "tofu",
    "label": "🥢 Tofu & Protein",
    "items": [
      {"name": "Extra-firm tofu",      "recipes": ["tofu-scramble", "tikka-masala"]},
      {"name": "Firm tofu",            "recipes": ["miso-noodles", "thai-curry"]},
    ]
  },
]

# ── GENERAL PANTRY ─────────────────────────────────────────────────────────
# Items you always want stocked, not tied to any single recipe.
# These appear under the "General" filter.

GENERAL_PANTRY = [
  # Oils & basics
  {"name": "Extra virgin olive oil",  "category": "Oils & Basics"},
  {"name": "Neutral cooking oil (vegetable / sunflower)", "category": "Oils & Basics"},
  {"name": "Sea salt (flaky + fine)", "category": "Oils & Basics"},
  {"name": "Black pepper (whole, for grinding)", "category": "Oils & Basics"},
  {"name": "Apple cider vinegar",     "category": "Oils & Basics"},
  # Pantry staples
  {"name": "Canned chickpeas (×3)",   "category": "Pantry Staples"},
  {"name": "Canned tomatoes (×4)",    "category": "Pantry Staples"},
  {"name": "Canned coconut milk (×2)","category": "Pantry Staples"},
  {"name": "Vegetable stock (cartons / cubes)", "category": "Pantry Staples"},
  {"name": "Red lentils",             "category": "Pantry Staples"},
  {"name": "Quinoa",                  "category": "Pantry Staples"},
  {"name": "Brown rice",              "category": "Pantry Staples"},
  {"name": "Soy sauce / tamari",      "category": "Pantry Staples"},
  {"name": "Tahini",                  "category": "Pantry Staples"},
  {"name": "Honey",                   "category": "Pantry Staples"},
  # Spice rack
  {"name": "Cumin (ground)",          "category": "Spice Rack"},
  {"name": "Smoked paprika",          "category": "Spice Rack"},
  {"name": "Turmeric",                "category": "Spice Rack"},
  {"name": "Garam masala",            "category": "Spice Rack"},
  {"name": "Chilli flakes",           "category": "Spice Rack"},
  {"name": "Dried oregano",           "category": "Spice Rack"},
  {"name": "Cinnamon (ground)",       "category": "Spice Rack"},
  # Fridge staples
  {"name": "Eggs (×6)",               "category": "Fridge Staples"},
  {"name": "Greek yogurt (large tub)","category": "Fridge Staples"},
  {"name": "Feta cheese",             "category": "Fridge Staples"},
  {"name": "Parmesan (block)",        "category": "Fridge Staples"},
  {"name": "Lemons (×3)",             "category": "Fridge Staples"},
  {"name": "Garlic (bulb)",           "category": "Fridge Staples"},
  {"name": "Fresh ginger (root)",     "category": "Fridge Staples"},
  # Snack staples
  {"name": "Almonds",                 "category": "Snack Staples"},
  {"name": "Almond butter",           "category": "Snack Staples"},
  {"name": "Dark chocolate (70%+)",   "category": "Snack Staples"},
  {"name": "Rice cakes (whole-grain)","category": "Snack Staples"},
  {"name": "Hummus (ready-made)",     "category": "Snack Staples"},
]
