"""
weekly_agent.py
Run by the Cowork weekly schedule. Reads the most recent cooking_log_*.json
in the workspace, finds the most-used ingredients, and appends 2 new
recipe suggestions to recipe_data.py, then regenerates the cookbook.

Usage (manual): python3 weekly_agent.py
Usage (automated): invoked by Cowork schedule every Sunday
"""
import json, os, glob, sys, re
from collections import Counter
from datetime import datetime

WORKSPACE = os.path.join(os.path.dirname(__file__), "mnt", "Grocery List")
RECIPE_DATA_FILE = os.path.join(os.path.dirname(__file__), "recipe_data.py")
BUILD_SCRIPT = os.path.join(os.path.dirname(__file__), "build_cookbook.py")

def find_latest_log():
    """Find the most recent cooking_log JSON file."""
    pattern = os.path.join(WORKSPACE, "cooking_log_*.json")
    files = sorted(glob.glob(pattern), reverse=True)
    if not files:
        # Also check current directory
        files = sorted(glob.glob("cooking_log_*.json"), reverse=True)
    return files[0] if files else None

def load_recipe_data():
    """Import current recipe list."""
    sys.path.insert(0, os.path.dirname(RECIPE_DATA_FILE))
    from recipe_data import RECIPES
    from grocery_data import GROCERY_CATEGORIES, RECIPE_NAMES
    return RECIPES, GROCERY_CATEGORIES, RECIPE_NAMES

def get_top_ingredients(made_ids, recipe_ingredients_map):
    """Return the top 5 most-used ingredients from the cooked recipes."""
    counter = Counter()
    for rid in made_ids:
        for ing in recipe_ingredients_map.get(rid, []):
            counter[ing] += 1
    return [item for item, _ in counter.most_common(5)]

def append_recipe_to_data(recipe_dict):
    """Append a new recipe dict to recipe_data.py before the closing bracket."""
    with open(RECIPE_DATA_FILE, "r") as f:
        content = f.read()
    # Find the closing bracket of RECIPES list
    insert_marker = "\n]\n"
    recipe_str = f"""
  # ── AUTO-ADDED {datetime.now().strftime('%Y-%m-%d')} ──────────────────────
  {{
    "id": "{recipe_dict['id']}",
    "name": "{recipe_dict['name']}",
    "tier": "{recipe_dict['tier']}", "tier_label": "{recipe_dict['tier_label']}",
    "chef": "{recipe_dict['chef']}",
    "description": "{recipe_dict['description']}",
    "time": "{recipe_dict['time']}", "servings": "{recipe_dict['servings']}",
    "ingredients": {json.dumps(recipe_dict['ingredients'])},
    "steps": {json.dumps(recipe_dict['steps'])},
    "macros": {json.dumps(recipe_dict['macros'])},
    "perf_tip": "{recipe_dict['perf_tip']}"
  }},
"""
    new_content = content.replace(insert_marker, recipe_str + insert_marker)
    with open(RECIPE_DATA_FILE, "w") as f:
        f.write(new_content)
    print(f"  ✅  Appended: {recipe_dict['name']}")

def write_summary(new_recipes, top_ingredients, log_data):
    """Write a human-readable summary of what the agent did."""
    summary_path = os.path.join(WORKSPACE, f"weekly_summary_{datetime.now().strftime('%Y-%m-%d')}.md")
    lines = [
        f"# Weekly Cookbook Update — {datetime.now().strftime('%B %d, %Y')}",
        "",
        f"## Recipes made this week ({len(log_data.get('recipes_made', []))})",
    ]
    for r in log_data.get("recipes_made", []):
        lines.append(f"- {r['name']} ({r.get('date','')})")
    lines += [
        "",
        f"## Top ingredients this week",
    ]
    for ing in top_ingredients:
        lines.append(f"- {ing}")
    lines += [
        "",
        "## 2 New recipes added to your cookbook",
    ]
    for r in new_recipes:
        lines.append(f"- **{r['name']}** ({r['tier_label']}) — inspired by {r['chef']}")
    lines += ["", "---", "_Generated by the Cowork weekly agent_"]
    with open(summary_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  📄  Summary: {summary_path}")
    return summary_path

# ── Recipe generation ──────────────────────────────────────────────────────
# The agent (Claude) reads this function's logic and generates recipes.
# When run manually or via schedule, Claude fills in these suggestions
# based on the top ingredients. The placeholders below are templates
# that Claude's agent task will replace with real recipes each week.

def generate_recipes_from_ingredients(top_ingredients):
    """
    INSTRUCTION FOR CLAUDE AGENT:
    Read the top_ingredients list, then create 2 new vegetarian recipes that:
    1. Feature at least 2 of these top ingredients
    2. Are performance/endurance optimised (high complex carbs + adequate protein)
    3. Are NOT already in recipe_data.py
    4. Follow the same dict structure as existing recipes
    5. Vary the tier (one easy/grab, one moderate/batch preferred)
    6. Are inspired by a real, named chef
    Return a Python list of exactly 2 recipe dicts.
    """
    # This function is populated by the Claude agent at runtime.
    # For manual testing, it returns example stubs.
    print(f"\n  🤖  Top ingredients to build around: {', '.join(top_ingredients)}")
    print("  ℹ️   Claude agent will generate 2 new recipes based on these.")
    print("  ℹ️   Recipes will be appended to recipe_data.py automatically.\n")
    return []  # Claude agent replaces this return with actual recipes

def run():
    print(f"\n🌿 Weekly Recipe Agent — {datetime.now().strftime('%A %B %d, %Y')}")
    print("─" * 50)

    # 1. Find cooking log
    log_path = find_latest_log()
    if not log_path:
        print("  ⚠️  No cooking_log_*.json found in workspace.")
        print("     Open the cookbook, mark recipes as made, and click 'Log Week & Save'.")
        return

    with open(log_path) as f:
        log_data = json.load(f)
    made_ids = [r["id"] for r in log_data.get("recipes_made", [])]
    print(f"  📋  Found log: {os.path.basename(log_path)}")
    print(f"  🍽   Recipes cooked: {len(made_ids)}")

    # 2. Load ingredient map
    RECIPES, GROCERY_CATEGORIES, RECIPE_NAMES = load_recipe_data()
    recipe_ingredients_map = {}
    for cat in GROCERY_CATEGORIES:
        for item in cat["items"]:
            for rid in item["recipes"]:
                recipe_ingredients_map.setdefault(rid, []).append(item["name"])

    # 3. Find top ingredients
    top_ingredients = get_top_ingredients(made_ids, recipe_ingredients_map)
    if not top_ingredients:
        top_ingredients = ["chickpeas", "quinoa", "tofu", "lemon", "spinach"]
    print(f"  🥬  Top ingredients: {', '.join(top_ingredients)}")

    # 4. Generate 2 new recipes (Claude agent fills this in)
    new_recipes = generate_recipes_from_ingredients(top_ingredients)

    if new_recipes:
        for r in new_recipes:
            append_recipe_to_data(r)
        # 5. Rebuild the cookbook
        print("\n  🔨  Rebuilding cookbook...")
        os.system(f"python3 '{BUILD_SCRIPT}'")
        # 6. Write summary
        summary_path = write_summary(new_recipes, top_ingredients, log_data)
        print(f"\n✅  Done! Cookbook updated with {len(new_recipes)} new recipes.")
    else:
        print("\n  ℹ️  Agent will add recipes when run via schedule.")

if __name__ == "__main__":
    run()
